### ISSUE TITLE
dual should not be taking voltage info from CAN bus

### ISSUE THREAD

**Issue by rusefillc** [dron0gus/wideband#12]
See https://rusefi.com/forum/viewtopic.php?p=48149#p48149

**Comment by rusefillc** [comment]
https://github.com/rusefi/wideband/commit/5a57147342d83534e62cb70a924ad6dbdbc41083

**Comment by dron0gus** [comment]
Fixed in https://github.com/dron0gus/wideband/commit/a3b5321cde78cd09b1e45c5973a08d3ec2dcbcec
