### ISSUE TITLE
afr config is overwritten by egt config

### ISSUE THREAD

**Issue by D0kRay** [dron0gus/wideband#16]
The afr config gets overwritten by the egt config in LoadDefaults() (f1_port.cpp) @dron0gus 
Line 81- ff
![image](https://github.com/dron0gus/wideband/assets/50095938/d5289632-f8bf-4c26-a1e8-879a539305ca)

**Comment by dron0gus** [comment]
Thank you for report!
Fixed in https://github.com/dron0gus/wideband/commit/f54b7f165479c3c518c2dcf0d147d9fee9ffe3fb
