### ISSUE TITLE
Heater: switch to HeaterState::ClosedLoop from Preheat or WarmupRamp

### ISSUE THREAD

**Issue by dron0gus** [dron0gus/wideband#4]
...if sensor temp is high enough.
If supply drops below 8.5 during cranking we start heating from beginning: Preheat, then WarmupRamp and only after - ClosedLoop.
Add shortcut to ClosedLoop state if sensor is hot enough.

**Comment by rusefillc** [comment]
@dron0gus is this important or not?

**Comment by dron0gus** [comment]
Implemented in https://github.com/dron0gus/wideband/commit/fa042fb6f533793c4b81637b324aba44358f7f58
