### ISSUE TITLE
dual rev1 with only one sensor

### ISSUE THREAD

**Issue by rusefillc** [dron0gus/wideband#6]
i have sensor hooked to channel0
i have no sensor hooked to channel1

why on earth do I see numbers changing on channel1?

![image](https://user-images.githubusercontent.com/48498823/233491060-449f34e9-92ed-46aa-9f1d-a8b8ecfa7df3.png)

[2023-04-20_17.19.32.mlg.zip](https://github.com/dron0gus/wideband/files/11290569/2023-04-20_17.19.32.mlg.zip)

**Comment by dron0gus** [comment]
Caused by HW issue **ESR measurement crosstalk between channels (rev0 and rev1)**
See https://github.com/rusefi/rusefi-hardware/tree/main/lambda-x2
